const iconMap: Record<string, string> = {
  'clear-day': 'clear-day',
  'clear-night': 'clear-night',
  cloudy: 'cloudy',
  rain: 'rain',
  snow: 'snow',
  sleet: 'sleet',
  wind: 'wind',
  fog: 'fog',
  'partly-cloudy-day': 'partly-cloudy-day',
  'partly-cloudy-night': 'partly-cloudy-night',
  thunderstorm: 'thunderstorms',
  // Pirate expanded icons
  'mostly-clear-day': 'clear-day',
  'mostly-clear-night': 'clear-night',
  'mostly-cloudy-day': 'overcast-day',
  'mostly-cloudy-night': 'overcast-night',
  'possible-rain-day': 'partly-cloudy-day-rain',
  'possible-rain-night': 'partly-cloudy-night-rain',
  'possible-snow-day': 'partly-cloudy-day-snow',
  'possible-snow-night': 'partly-cloudy-night-snow',
  'possible-sleet-day': 'partly-cloudy-day-sleet',
  'possible-sleet-night': 'partly-cloudy-night-sleet',
  'possible-thunderstorm-day': 'thunderstorms-day',
  'possible-thunderstorm-night': 'thunderstorms-night',
  'possible-precipitation-day': 'partly-cloudy-day-rain',
  'possible-precipitation-night': 'partly-cloudy-night-rain',
  precipitation: 'rain',
  drizzle: 'drizzle',
  'light-rain': 'drizzle',
  'heavy-rain': 'rain',
  flurries: 'snow',
  'light-snow': 'partly-cloudy-day-snow',
  'heavy-snow': 'snow',
  'very-light-sleet': 'sleet',
  'light-sleet': 'sleet',
  'heavy-sleet': 'sleet',
  breezy: 'wind',
  'dangerous-wind': 'hurricane',
  mist: 'mist',
  haze: 'haze',
  'haze-day': 'haze-day',
  'haze-night': 'haze-night',
  smoke: 'smoke',
  mixed: 'rain',
  raindrop: 'raindrop',
}

export function getMeteoconName(pirateIcon: string): string {
  return iconMap[pirateIcon] || 'not-available'
}
